export const ResizeModuleConfig = {
    modules: [
        'DisplaySize',
        'Toolbar',
        'Resize',
    ],
    overlayStyles: {
        position: 'absolute',
        boxSizing: 'border-box',
        border: '1px dashed hsl(215, 20%, 65%)',
        borderRadius: '4px',
    },
    handleStyles: {
        position: 'absolute',
        height: '10px',
        width: '10px',
        backgroundColor: 'hsl(0, 0%, 100%)',
        border: '1px solid hsl(215, 16%, 80%)',
        borderRadius: '50%',
        boxSizing: 'border-box',
        opacity: '0.9',
        boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
    },
    displayStyles: {
        position: 'absolute',
        fontFamily: 'system-ui, -apple-system, sans-serif',
        fontSize: '12px',
        lineHeight: '1.2',
        padding: '4px 8px',
        textAlign: 'center',
        backgroundColor: 'hsl(0, 0%, 100%)',
        color: 'hsl(215, 16%, 30%)',
        border: '1px solid hsl(215, 16%, 85%)',
        borderRadius: '4px',
        boxSizing: 'border-box',
        opacity: '0.95',
        cursor: 'default',
        boxShadow: '0 2px 6px rgba(0, 0, 0, 0.08)',
    },
    toolbarStyles: {
        position: 'absolute',
        top: '-12px',
        right: '0',
        left: '0',
        height: '0',
        minWidth: '100px',
        fontFamily: 'system-ui, -apple-system, sans-serif',
        fontSize: '12px',
        lineHeight: '1.2',
        textAlign: 'center',
        color: 'hsl(215, 16%, 30%)',
        boxSizing: 'border-box',
        cursor: 'default',
    },
    toolbarButtonStyles: {
        display: 'inline-block',
        width: '24px',
        height: '24px',
        background: 'hsl(0, 0%, 100%)',
        border: '1px solid hsl(215, 16%, 85%)',
        borderRadius: '4px',
        verticalAlign: 'middle',
        marginLeft: '2px',
        marginRight: '2px',
        boxShadow: '0 1px 3px rgba(0, 0, 0, 0.06)',
        transition: 'all 0.2s ease',
    },
    toolbarButtonSvgStyles: {
        fill: 'hsl(215, 16%, 35%)',
        stroke: 'hsl(215, 16%, 35%)',
        strokeWidth: '1.5',
    },
};